#!/bin/sh

. "${HOME}/.cache/wal/colors.sh"

chosen=$(find ~/Books/* | dmenu -c -bw 3 -l 5 -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15")

if [ "$chosen" != "" ]; then
	zathura "$chosen"
fi
