#!/bin/sh

## WM Name
id_bloat=$(xprop -root _NET_SUPPORTING_WM_CHECK)
id=${id_bloat##* }
wm_bloat=$(xprop -id "$id" _NET_WM_NAME)

## Get system info
distro=$(. /etc/os-release ; echo "${ID}")
kernel="$(uname -sr | sed 's/-.*//')"
uptime="$(uptime -p | sed 's/up //')"
shell="$(basename ${SHELL})"
packages="$(pacman -Qq | wc -l)"
wm="$(echo $wm_bloat | cut -d'"' -f 2)"
term="$(pstree -As $$ | awk -F "---" '{print $2}')"
user="$(whoami)@$(hostname)"

## Define Colours
if [[ $1 = "--red" ]]; then
	bgaccent="$(tput setab 1)"
	accent="$(tput setaf 1)"
elif [[ $1 = "--green" ]]; then
	bgaccent="$(tput setab 2)"
	accent="$(tput setaf 2)"
elif [[ $1 = "--yellow" ]]; then
	bgaccent="$(tput setab 3)"
	accent="$(tput setaf 3)"
elif [[ $1 = "--blue" ]]; then
	bgaccent="$(tput setab 4)"
	accent="$(tput setaf 4)"
elif [[ $1 = "--magenta" ]]; then
	bgaccent="$(tput setab 5)"
	accent="$(tput setaf 5)"
elif [[ $1 = "--cyan" ]]; then
	bgaccent="$(tput setab 6)"
	accent="$(tput setaf 6)"
else
	bgaccent="$(tput setab 7)"
	accent="$(tput setaf 7)"
fi

bold="$(tput bold)"
white="$(tput setaf 7)"
yellow="$(tput setaf 3)"
red="$(tput setaf 1)"
blue="$(tput setaf 4)"
green="$(tput setaf 2)"
orange="$(tput setaf 8)"
violet="$(tput setaf 5)"
cyan="$(tput setaf 6)"
reset="$(tput sgr0)"
cbg="${reset}${bold}${bgaccent}${white}"
cr="${reset}"
c0="${reset}${bold}"
c1="${reset}${accent}"

t0="$(tput setaf 0)"

## Output

cat <<EOF
${c0}${c1}       /\        ${c0}${white}    USER       ${c0}${violet}${user}${reset}
${c0}${c1}      /  \       ${c0}${white}    DISTRO     ${c0}${red}${distro}${reset}
${c0}${c1}     /    \      ${c0}${white}    KERNEL     ${c0}${yellow}${kernel}${reset}
${c0}${c1}    /      \     ${c0}${white}    UPTIME     ${c0}${cyan}${uptime}${reset}
${c0}${c1}   /   ,,   \    ${c0}${white}    WM         ${c0}${blue}${wm}${reset}
${c0}${c1}  /   |  |   \   ${c0}${white}    SHELL      ${c0}${green}${shell}${reset}
${c0}${c1} /   ,'  ',   \  ${c0}${white}    PACKAGES   ${c0}${orange}${packages}${reset}
${c0}${c1}/__--      --__\ ${c0}${white}    TERMINAL   ${c0}${violet}${term}${reset}

${t0}🔷${cr}${red}🔷${cr}${green}🔷${cr}${yellow}🔷${cr}${blue}🔷${cr}${violet}🔷${cr}${cyan}🔷${cr}${white}🔷${cr}
EOF

